//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Kus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entity_Hotel_Kus : DbContext
    {
        public Entity_Hotel_Kus()
            : base("name=Entity_Hotel_Kus")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListaKlientow> ListaKlientow { get; set; }
        public virtual DbSet<Pokoje> Pokoje { get; set; }
        public virtual DbSet<Rezerwacje> Rezerwacje { get; set; }
        public virtual DbSet<StatusPokoju> StatusPokoju { get; set; }
        public virtual DbSet<Widok_Rezerwacje> Widok_Rezerwacje { get; set; }
        public virtual DbSet<Widok_StatusPokoju> Widok_StatusPokoju { get; set; }
    }
}
