//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Kus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        public int ID { get; set; }
        public System.DateTime DataOd { get; set; }
        public System.DateTime DataDo { get; set; }
        public int Pokoj { get; set; }
        public int Klient { get; set; }
    
        public virtual ListaKlientow ListaKlientow { get; set; }
        public virtual Pokoje Pokoje { get; set; }
    }
}
