//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Kus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widok_Rezerwacje
    {
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public System.DateTime DataOd { get; set; }
        public System.DateTime DataDo { get; set; }
        public string NumerPokoju { get; set; }
        public int Pojemnosc { get; set; }
    }
}
